// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Software_Engineering_Final_Project_Team_Primal_Animals.Data;

#nullable disable

namespace Software_Engineering_Final_Project_Team_Primal_Animals.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251123211535_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Software_Engineering_Final_Project_Team_Primal_Animals.Models.Alert", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("is_reviewed_by_clinician")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("sensor_frame_id")
                        .HasColumnType("int");

                    b.Property<string>("user_id")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("id");

                    b.HasIndex("sensor_frame_id");

                    b.HasIndex("user_id");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("Software_Engineering_Final_Project_Team_Primal_Animals.Models.ClinicianReply", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("clinician_id")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("comment_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("reply_text")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("clinician_id");

                    b.HasIndex("comment_id");

                    b.ToTable("clinician_replies");
                });

            modelBuilder.Entity("Software_Engineering_Final_Project_Team_Primal_Animals.Models.MetricRecord", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<double>("contact_area_percentage")
                        .HasColumnType("double");

                    b.Property<string>("metrics_json")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("peak_pressure_index")
                        .HasColumnType("int");

                    b.Property<int>("sensor_frame_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("time_stamp")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("user_id")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("id");

                    b.HasIndex("sensor_frame_id");

                    b.HasIndex("user_id");

                    b.ToTable("metric_records");
                });

            modelBuilder.Entity("Software_Engineering_Final_Project_Team_Primal_Animals.Models.Report", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("generated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("generated_by_clinician_id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("report_data_json")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("report_type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("time_period_covered")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("user_id")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("id");

                    b.HasIndex("generated_by_clinician_id");

                    b.HasIndex("user_id");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("Software_Engineering_Final_Project_Team_Primal_Animals.Models.Roles", b =>
                {
                    b.Property<string>("role_id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("role_id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Software_Engineering_Final_Project_Team_Primal_Animals.Models.SensorFrame", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("pressure_values_json")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("time_stamp")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("user_id")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("id");

                    b.HasIndex("user_id");

                    b.ToTable("sensor_frames");
                });

            modelBuilder.Entity("Software_Engineering_Final_Project_Team_Primal_Animals.Models.UserClinicianAssignment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("assigned_on")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("clinician_id")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("patient_id")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("id");

                    b.HasIndex("clinician_id");

                    b.HasIndex("patient_id");

                    b.ToTable("user_clinician_assignments");
                });

            modelBuilder.Entity("Software_Engineering_Final_Project_Team_Primal_Animals.Models.UserComment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("comment_text")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("sensor_frame_id")
                        .HasColumnType("int");

                    b.Property<string>("user_id")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("id");

                    b.HasIndex("sensor_frame_id");

                    b.HasIndex("user_id");

                    b.ToTable("user_comments");
                });

            modelBuilder.Entity("Software_Engineering_Final_Project_Team_Primal_Animals.Models.UserRoleMap", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("role_id")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("user_id")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("id");

                    b.HasIndex("role_id");

                    b.HasIndex("user_id");

                    b.ToTable("user_role_map");
                });

            modelBuilder.Entity("Software_Engineering_Final_Project_Team_Primal_Animals.Models.Users", b =>
                {
                    b.Property<string>("user_id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("creation_timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("hash_password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("user_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("user_id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Software_Engineering_Final_Project_Team_Primal_Animals.Models.Alert", b =>
                {
                    b.HasOne("Software_Engineering_Final_Project_Team_Primal_Animals.Models.SensorFrame", "SensorFrame")
                        .WithMany("Alerts")
                        .HasForeignKey("sensor_frame_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Software_Engineering_Final_Project_Team_Primal_Animals.Models.Users", "User")
                        .WithMany("alerts")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SensorFrame");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Software_Engineering_Final_Project_Team_Primal_Animals.Models.ClinicianReply", b =>
                {
                    b.HasOne("Software_Engineering_Final_Project_Team_Primal_Animals.Models.Users", "clinician")
                        .WithMany("clinician_replies")
                        .HasForeignKey("clinician_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Software_Engineering_Final_Project_Team_Primal_Animals.Models.UserComment", "comment")
                        .WithMany("replies")
                        .HasForeignKey("comment_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("clinician");

                    b.Navigation("comment");
                });

            modelBuilder.Entity("Software_Engineering_Final_Project_Team_Primal_Animals.Models.MetricRecord", b =>
                {
                    b.HasOne("Software_Engineering_Final_Project_Team_Primal_Animals.Models.SensorFrame", "frame")
                        .WithMany("MetricRecords")
                        .HasForeignKey("sensor_frame_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Software_Engineering_Final_Project_Team_Primal_Animals.Models.Users", "user")
                        .WithMany("metric_records")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("frame");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Software_Engineering_Final_Project_Team_Primal_Animals.Models.Report", b =>
                {
                    b.HasOne("Software_Engineering_Final_Project_Team_Primal_Animals.Models.Users", "generated_by_clinician")
                        .WithMany()
                        .HasForeignKey("generated_by_clinician_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Software_Engineering_Final_Project_Team_Primal_Animals.Models.Users", "user")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("generated_by_clinician");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Software_Engineering_Final_Project_Team_Primal_Animals.Models.SensorFrame", b =>
                {
                    b.HasOne("Software_Engineering_Final_Project_Team_Primal_Animals.Models.Users", "user")
                        .WithMany("sensor_frames")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("Software_Engineering_Final_Project_Team_Primal_Animals.Models.UserClinicianAssignment", b =>
                {
                    b.HasOne("Software_Engineering_Final_Project_Team_Primal_Animals.Models.Users", "clinician")
                        .WithMany("clinician_assignments")
                        .HasForeignKey("clinician_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Software_Engineering_Final_Project_Team_Primal_Animals.Models.Users", "patient")
                        .WithMany("patient_assignments")
                        .HasForeignKey("patient_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("clinician");

                    b.Navigation("patient");
                });

            modelBuilder.Entity("Software_Engineering_Final_Project_Team_Primal_Animals.Models.UserComment", b =>
                {
                    b.HasOne("Software_Engineering_Final_Project_Team_Primal_Animals.Models.SensorFrame", "sensor_frame")
                        .WithMany("UserComments")
                        .HasForeignKey("sensor_frame_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Software_Engineering_Final_Project_Team_Primal_Animals.Models.Users", "user")
                        .WithMany("user_comments")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("sensor_frame");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Software_Engineering_Final_Project_Team_Primal_Animals.Models.UserRoleMap", b =>
                {
                    b.HasOne("Software_Engineering_Final_Project_Team_Primal_Animals.Models.Roles", "role")
                        .WithMany("user_role_map")
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Software_Engineering_Final_Project_Team_Primal_Animals.Models.Users", "user")
                        .WithMany("user_role_map")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("role");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Software_Engineering_Final_Project_Team_Primal_Animals.Models.Roles", b =>
                {
                    b.Navigation("user_role_map");
                });

            modelBuilder.Entity("Software_Engineering_Final_Project_Team_Primal_Animals.Models.SensorFrame", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("MetricRecords");

                    b.Navigation("UserComments");
                });

            modelBuilder.Entity("Software_Engineering_Final_Project_Team_Primal_Animals.Models.UserComment", b =>
                {
                    b.Navigation("replies");
                });

            modelBuilder.Entity("Software_Engineering_Final_Project_Team_Primal_Animals.Models.Users", b =>
                {
                    b.Navigation("alerts");

                    b.Navigation("clinician_assignments");

                    b.Navigation("clinician_replies");

                    b.Navigation("metric_records");

                    b.Navigation("patient_assignments");

                    b.Navigation("sensor_frames");

                    b.Navigation("user_comments");

                    b.Navigation("user_role_map");
                });
#pragma warning restore 612, 618
        }
    }
}
